/* libusb_version.h -- autogenerated
*/
#define VERSION_MAJOR 1
#define VERSION_MINOR 1
#define VERSION_MICRO 14
#define VERSION_NANO  0

#define RC_VERSION 1,1,14,0
#define RC_VERSION_STR "1.1.14.0"
